name: flutter_keychain
description: Flutter secure storage via Keychain and Keystore
version: 1.0.0
homepage: https://github.com/MrPistoul/flutter_keychain

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mailinblack.flutterkeychain
        pluginClass: FlutterKeychainPlugin
      ios:
        pluginClass: FlutterKeychainPlugin
